### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [rasgan/arduino-libraries#1]
In the files
- PCF8574.cpp
- PCF8575.cpp
- DS3231.cpp

you wait after the Wire.requesFrom(). That is not needed: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by rasgan** [comment]
Maby. This is not my lib. I'm only use it in my projects.
